name: goodbyeVisuals
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pip:
    - pygame>=2.0.0
    - pytest>=7.0.0
    - black>=22.0.0
    - mypy>=0.950
    - pylint>=2.14.0
    - python-dotenv>=0.19.0
    - pydub>=0.25.1
    - scipy>=1.7.0
    - pyaudio